### ISSUE TITLE
Object Oriented SPICE module 

### ISSUE THREAD

**Issue by kidpixo** [openplanetary/op-data-cafe#13]

**Comment by michaelaye** [comment]
I actually got something like that. And the European SPICE wrapper I think as well?

**Comment by marcsit** [comment]
Well I would not call it a wrapper but yes, here's were the discussion started from. I will upload it on GitHub as soon as I can. Do you have anything to share?

**Comment by michaelaye** [comment]
I will work to add it to planetpy. What I created is a body-based surface calculator class with all the SPICE wrapped into readable methods.

**Comment by marcsit** [comment]
Nice conversation. I am now aware of planetpy :)
